### ISSUE TITLE
Building client "actions" / adding to the menu bar

### ISSUE THREAD

**Issue by fahrradflucht** [standardnotes/extensions-manager#1]
*This is probably misplaced here but I found no good place to put it. Sorry for that.*

I just had the idea to build a "publish snapshot to IPFS" action and was pumped to get started. But now I'm a bit disappointed to see that it looks like there is no easy way for an extension to add an item to the actions list or adding a menu "Menu Editor Actions"-Bar item.

Is that correct? What would have to change to make this possible?

**Comment by atmoio** [comment]
You're saying you want to create an extension that adds some items to the Actions menu? You can do this. Actions are extensions of their own. If you're building a component and want to add items to the menu, that would just need to be a separate extension. See here: https://docs.standardnotes.org/extensions/actions.html

**Comment by fahrradflucht** [comment]
Yeah I read this. But this requires me to have a service with an endpoint running somewhere or doesn't it?

**Comment by atmoio** [comment]
Yes, actions must hook into an API. How are you envisioning your action to work? Run some javascript locally?

**Comment by fahrradflucht** [comment]
Yes so either I would require the user to have a local IPFS gateway running or I would spawn a js-ipfs node in sn. But since it is just a simple sharing interaction that user only will want to do occasionally it does not really make sense to have a big chunk of your UI dedicated to this.

Sorry for the confusion maybe I'm just missing something. What exactly did you mean with:
> If you're building a component and want to add items to the menu, that would just need to be a separate extension.

**Comment by atmoio** [comment]
By component I mean one of the other extension types, like an editor, or a modal window (like CloudLink, or Action Bar). Those are the visual components that can run custom javascript and display custom html. I'd recommend creating an `editor-stack` extension to do what you're doing. This will be placed in a similar location as the Action Bar. It will have type `component` and area `editor-stack`.

**Comment by alandooz** [comment]
Maybe this issue could be close (also maybe the blog can handle some redirect from **/something.html to **/something ?)
