### ISSUE TITLE
Code for Listed can't be imported

### ISSUE THREAD

**Issue by leafcutterant** [standardnotes/extensions-manager#3]
This may belong to the repo of Listed, but that doesn't exist yet.

For me, if I try to import a generated extension code for the Listed module, nothing happens, even if I press enter.

**Comment by atmoio** [comment]
You're generating a code from the production Listed site? And you're pasting it inside "Import Extension" in the Extensions menu? If so and nothing happens, likely a copy/paste error. Make sure you're selecting the entire code when you copy it.

If still nothing, please open the dev console and see what errors you get on enter.

**Comment by leafcutterant** [comment]
Gotcha. What do these errors mean? (See screencap below.)

![clipboard011](https://user-images.githubusercontent.com/7106231/50566140-7bec7580-0d36-11e9-97db-2adca2b6827a.png)

**Comment by atmoio** [comment]
Hmm..hard to say without the actual URL. Can you email/slack me the author URL you're using? It would be secret in relation to the public, but not secret to the database admin of Listed, which would be me. So you aren't disclosing anything private to me. But I want to see if I can replicate it with the same URL. You should also try generating a new author link, making sure to copy it carefully, and see if that works.

**Comment by leafcutterant** [comment]
I tried it again and magically it just started to work. Would be nice to know what happened and why, but... not this time I guess.
